[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "24.8.0"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXTAUTH_URL = "https://your-site-name.netlify.app"